/**
 * The rule for "does this invoice already have an e-way bill", and a guard that
 * every decision asks it the same way.
 *
 * `generated` came through the portal integration; `recorded` was generated by
 * hand on the government portal and typed in. Four separate places decide
 * something on that basis — printing the number on the driver's challan,
 * refusing a local cancel, not transmitting a second bill for the same
 * consignment, and the compliance count. Each one used to spell the test out
 * for itself, and adding `recorded` to three of four would have been a quiet,
 * expensive bug: a duplicate e-way bill on the portal for one load.
 *
 * So the rule lives in one helper, and this fails if a site stops using it.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { hasEwayBill, EWAY_LIVE_STATUSES } from '../../dist/common/eway-status.util.js';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '../../../..');
const read = (p) => readFileSync(resolve(repoRoot, p), 'utf8');
/** Strip comments so these read code, not the prose that explains it. */
const stripComments = (src) =>
  src.replace(/\/\*[\s\S]*?\*\//g, '').replace(/(^|[^:])\/\/.*$/gm, '$1');

test('an e-way bill exists whether the portal or a person produced it', () => {
  assert.equal(hasEwayBill('generated'), true);
  assert.equal(hasEwayBill('recorded'), true);
  assert.equal(hasEwayBill('not_generated'), false);
  assert.equal(hasEwayBill('cancelled'), false);
  assert.equal(hasEwayBill(null), false);
  assert.equal(hasEwayBill(undefined), false);
  assert.equal(hasEwayBill(''), false);
  assert.deepEqual([...EWAY_LIVE_STATUSES].sort(), ['generated', 'recorded']);
});

test('every "does a bill exist" decision asks the same helper', () => {
  for (const file of [
    'apps/api/src/dispatch/delivery-challan.service.ts', // the driver's challan
    'apps/api/src/billing/invoice.service.ts', // refusing a local cancel
    'apps/api/src/compliance/gst-execution.service.ts', // never a second bill
  ]) {
    assert.match(read(file), /hasEwayBill/, `${file} must use the shared helper`);
  }
});

test('nothing decides a bill exists by comparing to "generated" alone', () => {
  // Two deliberate exceptions, both in invoice.service.ts: a number obtained
  // through the portal integration is authoritative and may not be typed over,
  // which is a question about PROVENANCE, not existence.
  const checked = {
    'apps/api/src/dispatch/delivery-challan.service.ts': 0,
    'apps/api/src/compliance/gst-execution.service.ts': 0,
    'apps/api/src/billing/invoice.service.ts': 2,
  };
  for (const [file, allowed] of Object.entries(checked)) {
    const hits = (stripComments(read(file)).match(/ewayStatus === 'generated'|eway === 'generated'/g) ?? []).length;
    assert.equal(
      hits,
      allowed,
      `${file}: ${hits} direct comparison(s) to 'generated', expected ${allowed}. ` +
        'A new one is how a recorded e-way bill gets forgotten on one side.',
    );
  }
});

test('the compliance count only ignores invoices that truly have a bill', () => {
  const agent = stripComments(read('apps/api/src/agents/specialist.agent.ts'));
  assert.match(
    agent,
    /eway_status = 'not_generated'/,
    'the pending count must key off not_generated, so any live status clears it',
  );
});
