/**
 * Which e-way bill statuses mean "a live e-way bill exists for this invoice".
 *
 * `generated` came through the portal integration; `recorded` was generated by
 * hand on the government portal and typed in. Until GST transmission is switched
 * on — which is every plant on day one — `recorded` is the only one that ever
 * occurs.
 *
 * For every decision that matters the two are the same thing:
 *   - the number is printed on the document the driver carries;
 *   - the invoice cannot be cancelled while it is live;
 *   - a second e-way bill is never generated for the same consignment;
 *   - the compliance check stops counting the invoice as "e-way bill pending".
 *
 * They are kept as separate values only so it is clear which system produced the
 * number. This lives in one place because the last four bugs of this shape were
 * a rule applied on one side of a pair and not the other.
 */
export const EWAY_LIVE_STATUSES: readonly string[] = ['generated', 'recorded'];

/** True when the invoice already has an e-way bill, however it was obtained. */
export function hasEwayBill(status: string | null | undefined): boolean {
  return EWAY_LIVE_STATUSES.includes(String(status ?? ''));
}
