/**
 * Standard API error codes (Design Doc 7 §26, Design Doc 11 §9.5).
 */
export const ERROR_CODES = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TENANT_SUSPENDED: 'TENANT_SUSPENDED',
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
  MODULE_NOT_ENABLED: 'MODULE_NOT_ENABLED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  PLANT_ACCESS_DENIED: 'PLANT_ACCESS_DENIED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',
  DUPLICATE_RECORD: 'DUPLICATE_RECORD',
  VERSION_CONFLICT: 'VERSION_CONFLICT',
  CREDIT_LIMIT_EXCEEDED: 'CREDIT_LIMIT_EXCEEDED',
  NEGATIVE_STOCK_APPROVAL_REQUIRED: 'NEGATIVE_STOCK_APPROVAL_REQUIRED',
  MIX_DESIGN_NOT_APPROVED: 'MIX_DESIGN_NOT_APPROVED',
  VEHICLE_NOT_AVAILABLE: 'VEHICLE_NOT_AVAILABLE',
  INVOICE_ALREADY_EXISTS: 'INVOICE_ALREADY_EXISTS',
  SYNC_CONFLICT: 'SYNC_CONFLICT',
  INTEGRATION_FAILED: 'INTEGRATION_FAILED',
  WHATSAPP_SEND_FAILED: 'WHATSAPP_SEND_FAILED',
  PLAN_LIMIT_EXCEEDED: 'PLAN_LIMIT_EXCEEDED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
