/**
 * Recording an e-way bill generated by hand on the government portal.
 *
 * The gap this closes: `eway_bill_no` was only ever written by the NIC
 * transmission path, which needs GSP credentials. Until those are configured —
 * which is every plant on day one — there was no way to record the 12-digit
 * number the portal gives you. Three things followed:
 *
 *   - the delivery challan the driver carries could never print it;
 *   - the invoice could be cancelled while a live e-way bill stood against it;
 *   - the compliance check counted every invoice over ₹50,000 as "e-way bill
 *     pending" forever. For a concrete plant that is every single load, so the
 *     warning was permanently red and therefore worthless.
 *
 * Env: API_BASE, LOGIN, RMC_PASSWORD, TEST_TENANT_ID, POSTGRES_*.
 */
import { randomUUID } from 'node:crypto';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const { DataSource } = require('typeorm');

const BASE = process.env.API_BASE ?? 'http://localhost:4000/api/v1';
const TENANT = process.env.TEST_TENANT_ID;
if (!TENANT) { console.error('TEST_TENANT_ID required'); process.exit(1); }

const owner = new DataSource({
  type: 'postgres',
  host: process.env.POSTGRES_HOST ?? '127.0.0.1',
  port: Number(process.env.POSTGRES_PORT ?? 5432),
  username: process.env.POSTGRES_USER ?? 'rmc_owner',
  password: process.env.POSTGRES_PASSWORD ?? 'ownerpw',
  database: process.env.POSTGRES_DB ?? 'rmc',
});
await owner.initialize();
const q = (sql, params) => owner.query(sql, params);
const one = async (sql, params) => (await owner.query(sql, params))[0];

let passed = 0;
let failed = 0;
function ok(cond, label) {
  if (cond) { passed++; console.log(`  ✓ ${label}`); } else { failed++; console.log(`  ✗ ${label}`); }
}

const loginRes = await fetch(`${BASE}/auth/login`, {
  method: 'POST', headers: { 'Content-Type': 'application/json' },
  body: JSON.stringify({ login: process.env.LOGIN, password: process.env.RMC_PASSWORD }),
}).then((r) => r.json());
const TOKEN = loginRes?.data?.access_token;
if (!TOKEN) { console.error('login failed', JSON.stringify(loginRes)); process.exit(1); }
async function call(method, path, body) {
  const res = await fetch(`${BASE}${path}`, {
    method, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${TOKEN}` },
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  let json = null;
  try { json = await res.json(); } catch { json = null; }
  return { status: res.status, ok: res.ok, data: json?.data, msg: json?.error?.message ?? json?.message ?? '' };
}
const patch = (path, body) => call('PATCH', path, body);

const tag = Date.now().toString(36);
const customerId = randomUUID();
await q(
  `INSERT INTO customers (id, tenant_id, customer_code, customer_name, customer_type, state)
   VALUES ($1,$2,$3,$4,'company','Tamil Nadu')`,
  [customerId, TENANT, `EWB-${tag}`, `Eway Record ${tag}`],
);
const challanId = randomUUID();
await q(
  `INSERT INTO delivery_challans (id, tenant_id, challan_no, customer_id, quantity_m3, return_quantity_m3, challan_status, invoice_status)
   VALUES ($1,$2,$3,$4,60,0,'delivered','not_invoiced')`,
  [challanId, TENANT, `EWBC-${tag}`, customerId],
);
// 60 m³ at ₹5,000 is ₹3,54,000 with GST — comfortably over the ₹50,000 e-way threshold.
const draft = await call('POST', '/invoices/from-challans', {
  customerId, lines: [{ challanId, rate: 5000, gstRate: 18, hsnSac: '3824' }],
});
const invoiceId = draft.data?.id;
if (!invoiceId) { console.error('could not draft an invoice', JSON.stringify(draft)); process.exit(1); }
await call('POST', `/invoices/${invoiceId}/issue`, {});

/** The exact count the compliance agent reports as "e-way bill pending". */
const pendingCount = async () =>
  Number(
    (await one(
      `SELECT count(*)::int AS c FROM invoices
        WHERE invoice_status NOT IN ('draft','cancelled') AND eway_status = 'not_generated'
          AND total_amount > 50000 AND id = $1`,
      [invoiceId],
    )).c,
  );

console.log('\n[1] a mistyped number is refused');
{
  for (const [bad, why] of [['12345678901', 'eleven digits'], ['23123456789A', 'a letter'], ['', 'nothing at all']]) {
    const r = await patch(`/invoices/${invoiceId}/transport`, { ewayBillNo: bad });
    // An empty string clears rather than failing — that is how you remove a number.
    if (bad === '') ok(r.ok, 'an empty value clears the number rather than erroring');
    else ok(!r.ok && /12 digits/.test(r.msg), `refused ${why}: ${r.msg}`);
  }
  const r = await patch(`/invoices/${invoiceId}/transport`, { ewayValidUntil: '2026-09-20' });
  ok(!r.ok, `a validity date with no number on file is refused: ${r.msg}`);
}

console.log('\n[2] the number from the portal is recorded');
{
  ok((await pendingCount()) === 1, 'before: the compliance check counts this invoice as e-way bill pending');
  const r = await patch(`/invoices/${invoiceId}/transport`, {
    ewayBillNo: '2312 3456 7890', ewayValidUntil: '2026-09-20',
  });
  ok(r.ok, 'the 12-digit number is accepted');
  const inv = await one(`SELECT eway_bill_no, eway_status, eway_bill_date, eway_valid_until FROM invoices WHERE id = $1`, [invoiceId]);
  ok(inv.eway_bill_no === '231234567890', `spaces are stripped as typed from the portal (${inv.eway_bill_no})`);
  ok(inv.eway_status === 'recorded', `the status says where it came from (${inv.eway_status})`);
  ok(inv.eway_bill_date != null, 'the date it was generated is stamped');
  ok((await pendingCount()) === 0, 'after: the compliance check stops counting it — the warning can be trusted again');
}

console.log('\n[3] a live e-way bill blocks a local cancel');
{
  const r = await call('POST', `/invoices/${invoiceId}/cancel`, { reason: 'test' });
  ok(!r.ok && /e-way bill/i.test(r.msg), `cancel refused while the e-way bill stands: ${r.msg}`);
}

console.log('\n[4] the number reaches the document the driver carries');
{
  const pdf = async () => {
    const res = await fetch(`${BASE}/delivery-challans/${challanId}/pdf`, { headers: { Authorization: `Bearer ${TOKEN}` } });
    return Buffer.from(await res.arrayBuffer());
  };
  const withEwb = await pdf();
  ok(withEwb.subarray(0, 5).toString() === '%PDF-', 'the challan still renders a valid PDF');
  await q(`UPDATE invoices SET eway_status = 'not_generated' WHERE id = $1`, [invoiceId]);
  const without = await pdf();
  await q(`UPDATE invoices SET eway_status = 'recorded' WHERE id = $1`, [invoiceId]);
  ok(
    withEwb.length > without.length,
    `the e-way line is printed for a recorded bill, not only a transmitted one (${withEwb.length} vs ${without.length} bytes)`,
  );
}

console.log('\n[5] a bill obtained through the portal integration is protected');
{
  await q(`UPDATE invoices SET eway_status = 'generated', eway_bill_no = '999988887777' WHERE id = $1`, [invoiceId]);
  const r = await patch(`/invoices/${invoiceId}/transport`, { ewayBillNo: '231234567890' });
  ok(!r.ok && /portal/i.test(r.msg), `a transmitted number cannot be typed over: ${r.msg}`);
  const inv = await one(`SELECT eway_bill_no FROM invoices WHERE id = $1`, [invoiceId]);
  ok(inv.eway_bill_no === '999988887777', 'and it is left exactly as the portal returned it');
  await q(`UPDATE invoices SET eway_status = 'recorded', eway_bill_no = '231234567890' WHERE id = $1`, [invoiceId]);
}

console.log('\n[6] clearing it puts the invoice back');
{
  const r = await patch(`/invoices/${invoiceId}/transport`, { ewayBillNo: null });
  ok(r.ok, 'the number can be cleared');
  const inv = await one(`SELECT eway_bill_no, eway_status, eway_valid_until FROM invoices WHERE id = $1`, [invoiceId]);
  ok(inv.eway_bill_no === null && inv.eway_valid_until === null, 'the number and its validity go together');
  ok(inv.eway_status === 'not_generated', 'and the status returns to pending');
  ok((await pendingCount()) === 1, 'so the compliance check flags it again');
}

console.log(`\n${passed} passed, ${failed} failed`);
await owner.destroy();
process.exit(failed ? 1 : 0);
