import { test, expect, type Page } from '@playwright/test';

/**
 * Visual-regression BASELINE of the current production UI (flag OFF).
 *
 * First run WRITES the reference PNGs (per viewport project × theme); later UI
 * PRs re-run and DIFF against them — that is the regression net. Non-essential
 * animation is disabled and the network is idle before each shot, so a baseline
 * is never an unstable frame.
 *
 * Representative screens cover the owner's protected surfaces: routes, nav,
 * tables, forms, dialogs, an operational screen, a financial screen, the audit
 * trail (permissions), and the offline/sync (devices) screen.
 */

const STABILIZE = `
  *, *::before, *::after { transition: none !important; animation: none !important; }
  html { scroll-behavior: auto !important; }
  * { caret-color: transparent !important; }
`;

async function stabilize(page: Page) {
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.addStyleTag({ content: STABILIZE });
  await page.waitForLoadState('networkidle');
  // settle late async list/skeleton swaps
  await page.waitForTimeout(400);
}

// VISUAL_MODE selects the snapshot set: 'off' compares against the flag-OFF
// baselines (proving the default UI did NOT move); 'v2' is the flag-ON Deep
// Violet Matte set (its own '-v2' baselines).
const MODE = process.env.VISUAL_MODE === 'v2' ? 'v2' : 'off';
const SUFX = MODE === 'v2' ? '-v2' : '';

async function capture(page: Page, name: string, path: string) {
  // Light (default)
  await page.addInitScript(() => window.localStorage.setItem('mn-theme', 'light'));
  await page.goto(path, { waitUntil: 'networkidle' });
  await stabilize(page);
  await expect(page).toHaveScreenshot(`${name}-light${SUFX}.png`, { fullPage: true });

  // Dark (toggle persisted in localStorage, reload so the shell re-reads it)
  await page.evaluate(() => window.localStorage.setItem('mn-theme', 'dark'));
  await page.reload({ waitUntil: 'networkidle' });
  await stabilize(page);
  await expect(page).toHaveScreenshot(`${name}-dark${SUFX}.png`, { fullPage: true });
}

// Authenticated app surfaces (owner session via storageState), one entry per
// route across every nav group. Rendered against the freshly-seeded VISUAL
// tenant, so lists show their (deterministic) empty state and the seeded plant
// master — no per-run data drift.
//
// The 7 original names (dashboard, masters-customers, orders,
// production-batch-queue, billing-invoices, roles, devices-sync) are kept
// verbatim so their committed baselines still match; everything else is new
// coverage whose baselines are generated by the visual workflow (update mode).
//
// DELIBERATELY EXCLUDED (non-deterministic or unbaselinable), covered by the
// API integration/e2e suites instead:
//   • /app/audit            — per-run event timestamps
//   • /app/dispatch/tracking — live GPS fixes + relative "15s" refresh clock
//   • /app/assistant, /app/sales/import-po — AI-gated (hidden/disabled when AI off)
//   • every [id]/[name] detail route — needs a seeded record id
//   • /app (index)          — redirects to /app/dashboard
const SCREENS: Array<{ name: string; path: string }> = [
  // Overview
  { name: 'dashboard', path: '/app/dashboard' },
  { name: 'account', path: '/app/account' },
  // Setup
  { name: 'setup-company', path: '/app/company' },
  { name: 'users', path: '/app/users' },
  { name: 'roles', path: '/app/roles' },
  { name: 'numbering', path: '/app/numbering' },
  { name: 'imports', path: '/app/imports' },
  { name: 'settings', path: '/app/settings' },
  // Masters (all served by /app/entity/[name])
  { name: 'masters-plants', path: '/app/entity/plants' },
  { name: 'masters-number-series', path: '/app/entity/number-series' },
  { name: 'masters-customers', path: '/app/entity/customers' },
  { name: 'masters-sites', path: '/app/entity/sites' },
  { name: 'masters-materials', path: '/app/entity/materials' },
  { name: 'masters-uoms', path: '/app/entity/uoms' },
  { name: 'masters-uom-conversions', path: '/app/entity/uom-conversions' },
  { name: 'masters-suppliers', path: '/app/entity/suppliers' },
  { name: 'masters-vehicles', path: '/app/entity/vehicles' },
  { name: 'masters-drivers', path: '/app/entity/drivers' },
  { name: 'masters-transporters', path: '/app/entity/transporters' },
  { name: 'masters-grades', path: '/app/entity/concrete-grades' },
  // Sales
  { name: 'sales-leads', path: '/app/sales/leads' },
  { name: 'sales-quotations', path: '/app/sales/quotations' },
  { name: 'sales-rate-contracts', path: '/app/sales/rate-contracts' },
  { name: 'sales-order-drafts', path: '/app/sales/order-drafts' },
  // Orders
  { name: 'orders', path: '/app/orders' },
  { name: 'credit-holds', path: '/app/credit-holds' },
  // Production
  { name: 'production-mix-designs', path: '/app/production/mix-designs' },
  { name: 'production-plans', path: '/app/production/plans' },
  { name: 'production-batch-queue', path: '/app/production/batch-queue' },
  { name: 'production-batch-tickets', path: '/app/production/batch-tickets' },
  { name: 'production-stock', path: '/app/production/stock' },
  { name: 'production-reports', path: '/app/production/reports' },
  // Quality
  { name: 'qc-slump', path: '/app/qc/slump' },
  { name: 'qc-cubes', path: '/app/qc/cubes' },
  // Dispatch
  { name: 'dispatch-board', path: '/app/dispatch/board' },
  { name: 'dispatch-challans', path: '/app/dispatch/challans' },
  // Inventory
  { name: 'inventory-inward', path: '/app/inventory/inward' },
  { name: 'inventory-weighbridge', path: '/app/inventory/weighbridge' },
  { name: 'inventory-adjustments', path: '/app/inventory/adjustments' },
  { name: 'inventory-negative-stock', path: '/app/inventory/negative-stock' },
  { name: 'inventory-reports', path: '/app/inventory/reports' },
  // Purchase
  { name: 'purchase-orders', path: '/app/purchase/orders' },
  { name: 'purchase-bills', path: '/app/purchase/bills' },
  // Fleet
  { name: 'fleet-maintenance', path: '/app/fleet/maintenance' },
  { name: 'fleet-fuel', path: '/app/fleet/fuel' },
  // Expenses
  { name: 'expenses-vouchers', path: '/app/expenses/vouchers' },
  { name: 'expenses-heads', path: '/app/expenses/heads' },
  // Billing
  { name: 'billing-invoices', path: '/app/billing/invoices' },
  { name: 'billing-receipts', path: '/app/billing/receipts' },
  { name: 'billing-outstanding', path: '/app/billing/outstanding' },
  { name: 'billing-reports', path: '/app/billing/reports' },
  // Control
  { name: 'reports-center', path: '/app/reports' },
  { name: 'corrections', path: '/app/corrections' },
  { name: 'devices-sync', path: '/app/devices' },
];

for (const s of SCREENS) {
  test(`baseline: ${s.name}`, async ({ page }) => {
    await capture(page, s.name, s.path);
  });
}

// Login screen — captured unauthenticated (no session).
test.describe('unauthenticated', () => {
  test.use({ storageState: { cookies: [], origins: [] } });
  test('baseline: login', async ({ page }) => {
    await capture(page, 'login', '/login');
  });
});
